# Generated by Django 4.2.3 on 2023-08-09 22:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import events_management.user_profile.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_auth', '0002_appuser_profile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(10)])),
                ('website', models.URLField(blank=True, max_length=254, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(5)])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', validators=[events_management.user_profile.validators.validate_file_less_than_5mb])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('date_of_birth', models.DateField(validators=[events_management.user_profile.validators.check_if_date_is_future])),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Do not show', 'DO_NOT_SHOW')], max_length=11)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_photos/', validators=[events_management.user_profile.validators.validate_file_less_than_5mb])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
