# Generated by Django 4.2.3 on 2023-08-09 22:40

from django.db import migrations, models
import events_management.user_profile.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[events_management.user_profile.validators.check_if_date_is_future]),
        ),
    ]
