# Generated by Django 4.2.3 on 2023-07-11 22:21

from django.db import migrations, models
import events_management.user_profile.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', validators=[events_management.user_profile.validators.validate_file_less_than_5mb]),
        ),
    ]
