# Generated by Django 4.2.3 on 2023-07-12 02:55

from django.db import migrations, models
import events_management.user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Do not show', 'DO_NOT_SHOW')], default=events_management.user_profile.models.Gender['DO_NOT_SHOW'], max_length=11),
        ),
    ]
