# Generated by Django 4.2.3 on 2023-08-11 10:06

import django.core.validators
from django.db import migrations, models
import events_management.user_profile.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), events_management.user_profile.validators.validate_name_start_with_capital_letter]),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(5), events_management.user_profile.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), events_management.user_profile.validators.validate_name_start_with_capital_letter, events_management.user_profile.validators.validate_name_is_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), events_management.user_profile.validators.validate_name_start_with_capital_letter, events_management.user_profile.validators.validate_name_is_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(5), events_management.user_profile.validators.validate_phone_number]),
        ),
    ]
