# Generated by Django 4.2.3 on 2023-07-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Do not show', 'DO_NOT_SHOW')], max_length=11),
        ),
    ]
