# Generated by Django 4.2.3 on 2023-08-11 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_organizer_name_alter_organizer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
