# Generated by Django 4.2.3 on 2023-07-12 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_appuser_profile_type'),
        ('user_profile', '0004_alter_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
