# Generated by Django 4.2.3 on 2023-07-12 04:07

from django.db import migrations, models
import events_management.event.validators


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', validators=[events_management.event.validators.validate_file_less_than_5mb]),
        ),
    ]
