# Generated by Django 4.2.3 on 2023-07-28 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_organizer_logo_organizer_phone_number_and_more'),
        ('event', '0002_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, to='user_profile.organizer'),
            preserve_default=False,
        ),
    ]
