# Generated by Django 4.2.3 on 2023-08-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='phone_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
