# Generated by Django 4.2.3 on 2023-07-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_type',
            field=models.CharField(choices=[('normal', 'Normal User'), ('organizer', 'Organizer')], default='normal', max_length=10),
        ),
    ]
