# Generated by Django 4.2.3 on 2023-07-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_appuser_profile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='profile_type',
        ),
    ]
