# Generated by Django 4.2.3 on 2023-08-09 22:12

import django.core.validators
from django.db import migrations, models
import events_management.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('country', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(10)])),
                ('image', models.ImageField(upload_to='locations/', validators=[events_management.common.validators.validate_file_less_than_5mb])),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
